parameters:
    pirastru_form_builder.label: "Form Builder Drag&Drop"
    pirastru_form_builder.save_data: true
services:
    pirastru_form_builder.admin:
        class: Pirastru\FormBuilderBundle\Admin\FormBuilderAdmin
        arguments: [~, Pirastru\FormBuilderBundle\Entity\FormBuilder, PirastruFormBuilderBundle:FormBuilderAdmin, "@service_container"]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Form, label: "%pirastru_form_builder.label%" }

    pirastru_form_builder.submitted_value_admin:
        class: Pirastru\FormBuilderBundle\Admin\SubmittedValueAdmin
        arguments: [~, Pirastru\FormBuilderBundle\Entity\SubmittedValue, PirastruFormBuilderBundle:SubmittedValueAdmin, "@service_container"]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Form, label: "%pirastru_form_builder.label%" }

    pirastru_form_builder.submitted_form_admin:
        class: Pirastru\FormBuilderBundle\Admin\SubmittedFormAdmin
        arguments: [~, Pirastru\FormBuilderBundle\Entity\SubmittedForm, PirastruFormBuilderBundle:SubmittedFormAdmin, "@service_container"]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Form, label: "%pirastru_form_builder.label%" }            

    pirastru_form_builder.block:
        class: Pirastru\FormBuilderBundle\Block\FormBuilderBlockService
        arguments:
            - "pirastru_form_builder.block"
            - "@templating"
        tags:
            - {name: "sonata.block"}

    pirastru_form_builder.controller:
        class: Pirastru\FormBuilderBundle\Controller\FormBuilderController
        calls:
            - [setContainer, ["@service_container"]]
