parameters:
    pirastru_form_builder.label: "Form Builder Drag&Drop"
    pirastru_form_builder.save_data: true
services:
    pirastru_form_builder.admin:
        class: Pirastru\FormBuilderBundle\Admin\FormBuilderAdmin
        tags:
            - {
                name: sonata.admin, 
                manager_type: orm, 
                group: Form, 
                label: "%pirastru_form_builder.label%",
                model_class: Pirastru\FormBuilderBundle\Entity\FormBuilder,
                controller: Pirastru\FormBuilderBundle\Controller\FormBuilderAdminController
            }
        calls:
          - [ setTemplates, [{ edit: '@@PirastruFormBuilder/CRUD/formbuilder.html.twig' }]]

    pirastru_form_builder.submitted_value_admin:
        class: Pirastru\FormBuilderBundle\Admin\SubmittedValueAdmin
        tags:
            - {
                name: sonata.admin, 
                manager_type: orm, 
                group: Form, 
                label: "%pirastru_form_builder.label%",
                model_class: Pirastru\FormBuilderBundle\Entity\SubmittedValue,
                controller: Pirastru\FormBuilderBundle\Controller\SubmittedValueAdminController
            }

    pirastru_form_builder.submitted_form_admin:
        class: Pirastru\FormBuilderBundle\Admin\SubmittedFormAdmin
        tags:
            - {
                name: sonata.admin, 
                manager_type: orm, 
                group: Form, 
                label: "%pirastru_form_builder.label%",
                model_class: Pirastru\FormBuilderBundle\Entity\SubmittedForm,
                controller: Pirastru\FormBuilderBundle\Controller\SubmittedFormAdminController
            }            

    pirastru_form_builder.block:
        class: Pirastru\FormBuilderBundle\Block\FormBuilderBlockService
        arguments:
            - "pirastru_form_builder.block"
            - "@templating"
        tags:
            - {name: "sonata.block"}

    pirastru_form_builder.controller:
        class: Pirastru\FormBuilderBundle\Controller\FormBuilderController
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - {name: "controller.service_arguments"}

    pirastru_form_builder.admin.controller:
        class: Pirastru\FormBuilderBundle\Controller\FormBuilderAdminController
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - {name: "controller.service_arguments"}
